### ISSUE TITLE
OutPut file for cleartext credentials

### ISSUE THREAD

**Issue by dimaspencer84** [NullArray/Bash-Kit-Multitool#2]
Hi ! I think there might be a problem on the cleartext credentials module. We are not able to insert the path towards the output file.
On the 162 line, I saw "reap" instead of "read". Can you check it out ?
Thanks for your tool ! ;-)

**Comment by NullArray** [comment]
Hey sorry for getting back at you so late. The machine i do my development on broke recently and i've been busy arranging repairs. I will look into this. But i see someone made a PR for this issue. i will check it out and if everything's alright i will merge! Thanks for your patience.

**Comment by NullArray** [comment]
Done!

https://github.com/NullArray/MIDA-Multitool/commit/92acc5b01bd4f9d76a56f68017755c75ce43f628
